---
- hosts: tag_Name_M5_ag_server[0] 
  gather_facts: no
  module_defaults:
   group/aws:
    region: us-east-1
  tasks:
   - name: get rds info
     rds_instance_facts: 
      db_instance_identifier: mod5-db-id
     register: db_instance_id
   - name: Run rds script
     ansible.builtin.command:
      argv:
       - ./scripts/initDb.sh
       - hostvars['localhost'][my_rds_db.endpoint.address]
